### ISSUE TITLE
WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#count defined in Enumerable

### ISSUE THREAD

**Issue by albertobissacco** [agilie/instagram_api_gem#5]
When i retrieve all my likes with "InstagramApi.user.liked_media" it give me this message:

`W, [2018-03-04T14:29:57.749690 #32581]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#count defined in Enumerable. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.`

**Comment by SergeyMell** [comment]
It's not an issue with a gem itself, but with `Hashie::Mash` which is used for results parsing. You can find appropriate issue here https://github.com/intridea/hashie/issues/423
However, it doesn't break anything. If your prefer, you can disable the warnings by setting
```
class Response < Hashie::Mash
  disable_warnings
end
```

**Comment by SergeyMell** [comment]
@albertobissacco, are you satisfied with my answer and I can close the issue?

**Comment by albertobissacco** [comment]
@SergeyMell yes, thank you! 😄
